version: 0.2
env:
  parameter-store:
    DB_PASSWORD: "/BACKEND/PROD/DB_PASSWORD"
    PAYTM_MID: "/BACKEND/PROD/PAYTM_MID"
 
phases:
  install:
    runtime-versions:
      java: corretto8
    commands: 
    - echo installing maven...
    - apt-get update -y
    - wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
    - yq --version
  build:
    commands:
    - printenv
    - echo Build started on `date`
    - yq eval --inplace  '.spring.datasource[0].password = 'DB_PASSWORD'' src/main/resources/application.yml
    - yq e -i '.paytm.keys.mid = env($PAYTM_MID)' src/main/resources/application.yml
    - cat src/main/resources/application.yml
artifacts:
  files:
    - "**/*"  
